// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALTKcvL8Ftcl2D1UcefdIQAG87QSA21Ro',
    appId: '1:443076766052:android:dead2d3632a2211a863271',
    messagingSenderId: '443076766052',
    projectId: 'spocepicker',
    databaseURL: 'https://spocepicker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spocepicker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuHMua5fF2oQCOf3WSaAQrlDdQtjSyQMM',
    appId: '1:443076766052:ios:4bf159e1b4105d24863271',
    messagingSenderId: '443076766052',
    projectId: 'spocepicker',
    databaseURL: 'https://spocepicker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spocepicker.firebasestorage.app',
    iosBundleId: 'com.example.pickleballApp',
  );
}
